"""add avatar

Revision ID: 7e27d710f519
Revises: 14266210a9c6
Create Date: 2025-07-18 08:52:06.239193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e27d710f519'
down_revision: Union[str, None] = '14266210a9c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avatars',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('app_bundle', sa.String(), nullable=False),
    sa.Column('heygen_group_id', sa.String(), nullable=False),
    sa.Column('heygen_id', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('avatars_pkey'))
    )
    op.create_index(op.f('avatars_id_idx'), 'avatars', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('avatars_id_idx'), table_name='avatars')
    op.drop_table('avatars')
    # ### end Alembic commands ###
